### PR TITLE
added some variables I call from other extensions

### PR DESCRIPTION
**Pull request by Farratto**
I'm sorry, I did not alphabetize them.  Did not have an easy way to do that.  I was hoping you do

### CODE REVIEW

**Comment by bmos** [comment]
So this repo generates that file automatically, which means your changes are going to get overwritten.
If there are other extensions that you want included, you generally are better off forking the repo and modifying the GitHub actions files so that it will generate a file specific to the extensions you use.

**Comment by Farratto** [comment]
> So this repo generates that file automatically, which means your changes are going to get overwritten. If there are other extensions that you want included, you generally are better off forking the repo and modifying the GitHub actions files so that it will generate a file specific to the extensions you use.

okay thank you

**Comment by bmos** [comment]
You could make a PR against the headers file to include CampaignRegistry though!:
https://github.com/bmos/FG-luacheck/blob/main/.luacheckrc_header

**Comment by bmos** [comment]
And if you want help getting your fork set up to generate a config based on the extensions you want to include let me know :)

**Comment by Farratto** [comment]
Actually, I do need help.  I edited the mail.yml.  I believe I did it correctly.  I updated my fork and then synced the fork with yours.  Now, how do I make the github action execute?

**Pull request closed without merging**
