### PR TITLE
add global CampaignRegistry

### PR DESCRIPTION
**Pull request by Farratto**
PR sent for .luacheckrc_header, as recommended

### CODE REVIEW

**Comment by bmos** [comment]
Is there documentation on CampaignRegistry?
It's not listed: https://fantasygroundsunity.atlassian.net/wiki/spaces/FGCP/pages/996644556/API+-+Packages

**Comment by Farratto** [comment]
This is the only place I know of that it is mentioned.  I found it from the ruleset source code.  It is associated with the database file in the campaign root folder named CampaignRegistry.lua

https://fantasygroundsunity.atlassian.net/wiki/spaces/FGCP/pages/996644496/Ruleset+-+Scripting#Registries

**Comment by bmos** [comment]
How interesting!
It looks like there's also a global registry?
I didn't realize that all of that was being stored in Lua tables...

**Comment by Farratto** [comment]
Oh, I didn't know about the GlobalRegistry.lua, lol.  Looks like that file is in the root data folder for fantasy grounds.  Mine just has sound, dice, and death splat settings.  I think that normally these files are accessed using prebuilt functions, but I had a specific purpose where the function wasn't working and had to workaround by accessing the data directly.

**Pull request merged**
